### ISSUE TITLE
Flarum beta8 compatibility

### ISSUE THREAD

**Issue by basilky** [wuethrich44/flarum-ext-sso#11]
This extension is not compatible with new version of Flarum as per https://flagrow.io. Will this extension work properly with Flarum beta 8 ?

**Comment by fabwu** [comment]
Sorry but I don't have a test instance of Flarum to verify if this plugin still works. Have you run a test with the new beta?

**Comment by basilky** [comment]
I have tried to install this extension on Flarum beta 8. The extension installs successfully and signin works automatically on Flarum when I sign in on my main site. But, when I activate the extension through extension manager in Flarum, no dialog opens to configure the extension options like sign up page, homepage etc. So, the forum homepage is open to all for sign in and sign up. Also, I have noticed that after I sign out from main site, I'm still signed in on the forum, even though the remember cookie is cleared(I think this issue was with beta 7 also).

**Comment by fabwu** [comment]
Thanks for testing the extension but I fear they changed all the namespaces and other things which I can't fix in 5 minutes. If you've figured out how to fix everything I would really appreciate a PR.

**Comment by sampoyigi** [comment]
Submitted a PR. #12  :)

**Comment by fabwu** [comment]
Resolved #12
