### ISSUE TITLE
SSO between sudomains

### ISSUE THREAD

**Issue by maicol07** [wuethrich44/flarum-ext-sso#13]
Hi,
I have an SSO system on the `account` subdomain (for example `account.example.com`) and a Flarum installation on the `community` subdomain (`community.example.com`). This setup doesn't seem to work. Could you please add this feature?
Also, as you can see [here](https://discuss.flarum.org/d/5052-single-sign-on/149) a lot of people need your help!
Thanks

**Comment by fabwu** [comment]
I don't think that's possible as `account` can't set cookies for `community`. Only the parent domain (i.e. `example.com`) is allowed to do that. Due to this limitation I can't add this feature.
