### ISSUE TITLE
Hello there, can not seem to get this working

### ISSUE THREAD

**Issue by MostHated** [wuethrich44/flarum-ext-sso#6]
Hello there. I wanted to post this here in hopes that you might see it, as it looks like you have not posted on Flarum forums since November. Here is what I had said.

"Hey there, I am unable to get this to work unfortunately. When I sign up, it creates the user in WP, when I login it takes me to the WP user page. If I go to my forum and login, it takes me to the WP page, I login, it then finally takes me back to the forum but I am not logged in, it just has the sign up or login button again and continues to do so. If I go to WP it shows me as logged in there it just is not transferring over to Flarum for some reason.

I, of course, have the api_key and what not in the db and did everything that was shown in the instructions.

I have these in the access log, but nothing I am seeing wrong in the error log

[12/Feb/2018:22:33:45 +0000] "GET /wp-login.php?redirect_to=forum HTTP/1.1" 200 1600 "https://changed_for_security/forum/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
[12/Feb/2018:22:33:48 +0000] "POST /forum/api/token HTTP/1.1" 401 3399 "-" "-"
[12/Feb/2018:22:33:48 +0000] "POST /forum/api/users HTTP/1.1" 422 3500 "-" "-"
[12/Feb/2018:22:33:48 +0000] "POST /forum/api/token HTTP/1.1" 401 3399 "-" "-"

Also, nothing related in the actual Flarum logs, it just simply isn't doing anything it seems.

My WP is in domain.com and forum is domain.com/forum if that makes any sort of difference. Everything else is working fine for both, just not logging in to the forum now.

I am assuming the random key I made up and put into the api_key in the db then goes into the config, and then I just type a random key into password token? I figured I would try it with nothing written in the api_key or password key fields and it acts the exact same was as when I do have the key in there and there are no errors or anything still."

**Comment by fabwu** [comment]
Sorry I can't reproduce your error. Let me know if you figured out how to fix it.

**Comment by MostHated** [comment]
I gave up on the whole forum a long time ago. Thanks though.
