### ISSUE TITLE
Unable to install "Your requirements could not be resolved to an installable set of packages."

### ISSUE THREAD

**Issue by adamlucia** [wuethrich44/flarum-ext-sso#9]
<img width="1224" alt="screenshot 2018-06-13 21 23 59" src="https://user-images.githubusercontent.com/2412941/41386744-07c64fce-6f51-11e8-8216-56ccd8d1cf79.png">

I'm following the instructions when I get this error...I'm unsure how to track down this issue. Any ideas?

**Comment by adamlucia** [comment]
Resolved by "make sure you are in the directory you installed Flarum in."

**Comment by fabwu** [comment]
Happened to me too once... I close this for you.
